ecom_elec/accounts/urls.py
from accounts .views import home,about,contact,cart

from django.urls import path
from . import views
from .views import Index

app_name = "accounts"


urlpatterns = [
        path("register", views.register_request, name="register"),
        path("login", views.login_request, name="login"),
        path('',Index.as_view(),name='index'),
        path('home/',home,name="home"),
        path('about/',about,name="about"),
        path('contact/',contact,name="contact"),
        path("cart/",cart,name="cart")


]

ecom_elec/ecom_elec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('electronics/',include("electronics.urls")),
    path('',include("accounts.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_elec/accounts/models.py
from django.db import models

# Create your models here.

ecom_elec/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

ecom_elec/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.views import View
# Create your views here.
from .forms import NewUserForm
from django.contrib.auth import logout
from django.shortcuts import redirect


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration Successful")
            return redirect("accounts:login")
        messages.error(request, "Unsuccessful registration.Invalid Information")
    form = NewUserForm()
    return render(request=request, template_name="accounts/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("list")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="accounts/login.html", context={"login_form": form})

class Index(View):
    def get(self,request,*args,**kwargs):
        return render(request,'accounts/home.html')


def home(request):
    template="accounts/home.html"
    context={}
    return render(request,template,context)

def about(request):
    template="accounts/about.html"
    context={}
    return render(request,template,context)

def contact(request):
    template="accounts/contact.html"
    context={}
    return render(request,template,context)

def cart(request):
    templates="accounts/cart.html"
    context={}
    return render(request,templates,context)


def signout(request):
    logout(request)
    return redirect('login')

ecom_elec/templates/accounts/about.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Option 1: Include in HTML -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <style>
	* {
	margin: 0;
	padding: 0;
}

html {
	scroll-behaviour: smooth;
}

:root {
	--navbar-height: 59px;
}

.navbar {
	display: flex;
	align-items: center;
	justify-content: center;
	position: sticky;
	color:black;
	top: 0;
	cursor: pointer;
}


.nav-list {
	width: 100%;
	display: flex;
}

.nav-list li {
	list-style: none;
	padding: 0px 6px;
}

.nav-list li a {
	text-decoration: none;
	color: white;
	font-size:20px;
}

.nav-list li a:hover {
text-decoration:none;
	color: Black;
}

.background {
	background-color: black;
	background-blend-mode: darken;
	background-size: cover;
}
.footer { background:
 black; }
 p{
 margin: 1px 1px ;
 font-family:"Piazzolla", serif;
 }
.box{
align:center;
margin-left:25px;
margin-top:25px;
margin-right:25px;
margin-bottom:95px;
}
.text-footer {
	text-align: center;
    color:blue;

}
footer{	padding: 0px 0;
	font-family: "Ubuntu", sans-serif;
	display: flex;
	font-size:20px;
	font-color:blue;
	bottom:0px;
	margin-bottom:0px;
	justify-content: center;
}


    </style>
</head>
<body>
<nav class="navbar background">

		<!-- Creating the list of
			items -->
		<ul class="nav-list">
			<li><a href="{% url 'accounts:home' %}">Home</a></li>
			<li><a href="#Topics"></a></li>
			<li><a href="{% url 'accounts:contact' %}">Contact Us</a></li>
			<li><a href="{%url 'accounts:about' %}">About Us</a></li>
		</ul>
</nav>
<div class="box">
     <h1 align="center">About Us</h1>
    <p style="color: black; font-size: 20px; align="left"> New and used electronics
    Some electronic stores carry new products that you can purchase.
        However, there are times when the store has a section for pre-owned items as well.
        This is great if you’re looking to save some money on your purchase but still want high-quality things.
        Extended warranty If you’re worried about your device breaking down
        then an extended warranty may be the right choice for you.
        You can find this option with many electronic stores, and it will cover any malfunctions
        or damages that happen to occur after purchase. It is great if something unexpected occurs.
        Shop online Many electronic stores will also sell their items through their website
        so that you can shop for your new gadget from the comfort of your computer.
        Some websites are available 24 hours a day, while others have limited availability depending on time zones.
        Regardless, it’s convenient to be able to get what you need without having to leave home.
    Accessories
    Electronics stores will also offer accessories for your devices.
        You can find anything you need to go along with what you just bought!
        From chargers to cases, the store is sure to have exactly what you’re looking for.
    Expert advice
    Lastly, many electronic stores will hire experts who are
        knowledgeable on all the products offered. They can help you make
        an informed purchase and ensure that you get what is best for your needs!
        This is especially great if it’s your first time buying something like this or
        you don’t know much about electronics in general.
    Gift cards
    Many electronic stores will offer
        gift cards for special occasions like birthdays or holidays.
        This is a great option because you can get something they want
        without having to guess what it might be! The store may also have
        promotional offers where if you spend a certain amount, the card won’t cost you anything


     Return policy
    Lastly, most electronic stores
        will have a return policy if you’re not
        satisfied with your purchase.
        It is especially great if it’s because of damage or
        faulty workmanship. The store should always offer some
        refund for these items so don’t worry.
    Other offers
    There are many other things that
        an electronic store may offer as well.
        Depending on the shop, you might find discounts
        for your next purchase if you’ve made a return in the past,
        or they always have special deals going on like buy one get one free.

</div>
    <!-- Footer -->
<footer class="background">
		<p class="text-footer">
			Copyright @-Dayelectronics
		</p>
	</footer>
<!-- Footer -->

</body>
</html>

ecom_elec/templates/accounts/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
{% include 'accounts/navbar.html' %}
{% block content %}
{% endblock %}

</body>
</html>

ecom_elec/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <!-- Option 1: Include in HTML -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <style>
    footer {
position: absolute;
bottom: 0;
width: 100%;
background-color: #333;
color:#fff;
}
* {
	margin: 0;
	padding: 0;
}

html {
	scroll-behaviour: smooth;
}

:root {
	--navbar-height: 59px;
}

.logo {
	width: 20%;
	display: flex;
	justify-content: center;
	align-items: center;
}

.logo img {
	width: 33%;
	border: 2px solid white;
	border-radius: 50px;
}

.navbar {
	display: flex;
	align-items: center;
	justify-content: center;
	position: sticky;
	top: 0;
	cursor: pointer;
}

.nav-list {
	width: 70%;
	display: flex;
}

.nav-list li {
	list-style: none;
	padding: 2px 6px;
}

.nav-list li a {
	text-decoration: none;
	color: white;
}

.nav-list li a:hover {
	color: grey;
}

.rightNav {
	width: 50;
	text-align: right;
}

#search {
	padding: 5px;
	font-size: 17px;
	border: 2px solid grey;
	border-radius: 9px;
}

.background {
	background-color: grey;
	background-blend-mode: darken;
	background-size: cover;
}

.firstsection {
	height: 100vh;
}

.box-main {
	display: flex;
	justify-content: center;
	align-items: center;
	color: white;
	max-width: 50%;
	margin: auto;
	height: 80%;
}

.firstHalf {
	width: 75%;
	display: flex;
	flex-direction: column;
	justify-content: center;
}

.firstHalf img {
	display: flex;
	border-radius: 9050px;
}

.text-big {
	font-family: "Piazzolla", serif;
	font-weight: bold;
	font-size: 41px;
	text-align: center;
}

.text-small {
	font-family: "Sansita Swashed", cursive;
	font-size: 18px;
	text-align: center;
}

#service {
	margin: 34px;
	display: flex;
}

#service .box {
	padding: 45px;
	margin: 3px 6px;
	border-radius: 28px;
}

#service .box img {
	margin-top: 20px;
	height: 100px;
	margin: auto;
	display: block;
	border-radius: 200px;
}

#service .box p {
	font-family: sans-serif;
	text-align: center;
}

.btn {
	padding: 8px 20px;
	margin: 7px 0;
	border: 2px solid white;
	border-radius: 8px;
	background: none;
	color: white;
	cursor: pointer;
}

.btn-sm {
	padding: 6px 10px;
	vertical-align: middle;
}

.center {
	text-align: center;
}

.text-footer {
	text-align: center;
	padding: 30px 0;
	font-family: "Ubuntu", sans-serif;
	display: flex;
	justify-content: center;
}
.text-box{
color:#000;
position:absolute;
bottom:18%;
margin-left:50px;
}
.text-box p{
font-size:150px;
font-weight:600;
}
.text-box h1{
font-size:190px;
line-height:160px;
margin-left:-10px;
color:transparent;
-webkit-text-stroke:1px #000;
background:url('https://images.pexels.com/photos/949587/pexels-photo-949587.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')
-webkit-background-clip:text;
background-position:0 0 ;
animation:back 20s linear infinite;
}
@keyframes back{
100%{
background-position:2000px 0;
}
}
.text-box h3{
font-size:40px;
font-weight:600;
}
#background-wrap {
    bottom: 0;
	left: 0;
	position: fixed;
	right: 0;
	top: 0;
	z-index: -1;
}

/* KEYFRAMES */

@-webkit-keyframes animateBubble {
    0% {
        margin-top: 1000px;
    }
    100% {
        margin-top: -100%;
    }
}

@-moz-keyframes animateBubble {
    0% {
        margin-top: 1000px;
    }
    100% {
        margin-top: -100%;
    }
}

@keyframes animateBubble {
    0% {
        margin-top: 1000px;
    }
    100% {
        margin-top: -100%;
    }
}

@-webkit-keyframes sideWays {
    0% {
        margin-left:0px;
    }
    100% {
        margin-left:50px;
    }
}

@-moz-keyframes sideWays {
    0% {
        margin-left:0px;
    }
    100% {
        margin-left:50px;
    }
}

@keyframes sideWays {
    0% {
        margin-left:0px;
    }
    100% {
        margin-left:50px;
    }
}

/* ANIMATIONS */

.x1 {
    -webkit-animation: animateBubble 25s linear infinite, sideWays 2s ease-in-out infinite alternate;
	-moz-animation: animateBubble 25s linear infinite, sideWays 2s ease-in-out infinite alternate;
	animation: animateBubble 25s linear infinite, sideWays 2s ease-in-out infinite alternate;

	left: -5%;
	top: 5%;

	-webkit-transform: scale(0.6);
	-moz-transform: scale(0.6);
	transform: scale(0.6);
}

.x2 {
    -webkit-animation: animateBubble 20s linear infinite, sideWays 4s ease-in-out infinite alternate;
	-moz-animation: animateBubble 20s linear infinite, sideWays 4s ease-in-out infinite alternate;
	animation: animateBubble 20s linear infinite, sideWays 4s ease-in-out infinite alternate;

	left: 5%;
	top: 80%;

	-webkit-transform: scale(0.4);
	-moz-transform: scale(0.4);
	transform: scale(0.4);
}

.x3 {
    -webkit-animation: animateBubble 28s linear infinite, sideWays 2s ease-in-out infinite alternate;
	-moz-animation: animateBubble 28s linear infinite, sideWays 2s ease-in-out infinite alternate;
	animation: animateBubble 28s linear infinite, sideWays 2s ease-in-out infinite alternate;

	left: 10%;
	top: 40%;

	-webkit-transform: scale(0.7);
	-moz-transform: scale(0.7);
	transform: scale(0.7);
}

.x4 {
    -webkit-animation: animateBubble 22s linear infinite, sideWays 3s ease-in-out infinite alternate;
	-moz-animation: animateBubble 22s linear infinite, sideWays 3s ease-in-out infinite alternate;
	animation: animateBubble 22s linear infinite, sideWays 3s ease-in-out infinite alternate;

	left: 20%;
	top: 0;

	-webkit-transform: scale(0.3);
	-moz-transform: scale(0.3);
	transform: scale(0.3);
}

.x5 {
    -webkit-animation: animateBubble 29s linear infinite, sideWays 4s ease-in-out infinite alternate;
	-moz-animation: animateBubble 29s linear infinite, sideWays 4s ease-in-out infinite alternate;
	animation: animateBubble 29s linear infinite, sideWays 4s ease-in-out infinite alternate;

	left: 30%;
	top: 50%;

	-webkit-transform: scale(0.5);
	-moz-transform: scale(0.5);
	transform: scale(0.5);
}

.x6 {
    -webkit-animation: animateBubble 21s linear infinite, sideWays 2s ease-in-out infinite alternate;
	-moz-animation: animateBubble 21s linear infinite, sideWays 2s ease-in-out infinite alternate;
	animation: animateBubble 21s linear infinite, sideWays 2s ease-in-out infinite alternate;

	left: 50%;
	top: 0;

	-webkit-transform: scale(0.8);
	-moz-transform: scale(0.8);
	transform: scale(0.8);
}

.x7 {
    -webkit-animation: animateBubble 20s linear infinite, sideWays 2s ease-in-out infinite alternate;
	-moz-animation: animateBubble 20s linear infinite, sideWays 2s ease-in-out infinite alternate;
	animation: animateBubble 20s linear infinite, sideWays 2s ease-in-out infinite alternate;

	left: 65%;
	top: 70%;

	-webkit-transform: scale(0.4);
	-moz-transform: scale(0.4);
	transform: scale(0.4);
}

.x8 {
    -webkit-animation: animateBubble 22s linear infinite, sideWays 3s ease-in-out infinite alternate;
	-moz-animation: animateBubble 22s linear infinite, sideWays 3s ease-in-out infinite alternate;
	animation: animateBubble 22s linear infinite, sideWays 3s ease-in-out infinite alternate;

	left: 80%;
	top: 10%;

	-webkit-transform: scale(0.3);
	-moz-transform: scale(0.3);
	transform: scale(0.3);
}

.x9 {
    -webkit-animation: animateBubble 29s linear infinite, sideWays 4s ease-in-out infinite alternate;
	-moz-animation: animateBubble 29s linear infinite, sideWays 4s ease-in-out infinite alternate;
	animation: animateBubble 29s linear infinite, sideWays 4s ease-in-out infinite alternate;

	left: 90%;
	top: 50%;

	-webkit-transform: scale(0.6);
	-moz-transform: scale(0.6);
	transform: scale(0.6);
}

.x10 {
    -webkit-animation: animateBubble 26s linear infinite, sideWays 2s ease-in-out infinite alternate;
	-moz-animation: animateBubble 26s linear infinite, sideWays 2s ease-in-out infinite alternate;
	animation: animateBubble 26s linear infinite, sideWays 2s ease-in-out infinite alternate;

	left: 80%;
	top: 80%;

	-webkit-transform: scale(0.3);
	-moz-transform: scale(0.3);
	transform: scale(0.3);
}

/* OBJECTS */

.bubble {
    -webkit-border-radius: 50%;
	-moz-border-radius: 50%;
	border-radius: 50%;

    -webkit-box-shadow: 0 20px 30px rgba(0, 0, 0, 0.2), inset 0px 10px 30px 5px rgba(255, 255, 255, 1);
	-moz-box-shadow: 0 20px 30px rgba(0, 0, 0, 0.2), inset 0px 10px 30px 5px rgba(255, 255, 255, 1);
	box-shadow: 0 20px 30px rgba(0, 0, 0, 0.2), inset 0px 10px 30px 5px rgba(255, 255, 255, 1);

    height: 200px;
	position: absolute;
	width: 200px;
}

.bubble:after {
    background: -moz-radial-gradient(center, ellipse cover,  rgba(255,255,255,0.5) 0%, rgba(255,255,255,0) 70%); /* FF3.6+ */
    background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(0%,rgba(255,255,255,0.5)), color-stop(70%,rgba(255,255,255,0))); /* Chrome,Safari4+ */
    background: -webkit-radial-gradient(center, ellipse cover,  rgba(255,255,255,0.5) 0%,rgba(255,255,255,0) 70%); /* Chrome10+,Safari5.1+ */
    background: -o-radial-gradient(center, ellipse cover,  rgba(255,255,255,0.5) 0%,rgba(255,255,255,0) 70%); /* Opera 12+ */
    background: -ms-radial-gradient(center, ellipse cover,  rgba(255,255,255,0.5) 0%,rgba(255,255,255,0) 70%); /* IE10+ */
    background: radial-gradient(ellipse at center,  rgba(255,255,255,0.5) 0%,rgba(255,255,255,0) 70%); /* W3C */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#80ffffff', endColorstr='#00ffffff',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */

	-webkit-border-radius: 50%;
	-moz-border-radius: 50%;
	border-radius: 50%;

    -webkit-box-shadow: inset 0 20px 30px rgba(255, 255, 255, 0.3);
	-moz-box-shadow: inset 0 20px 30px rgba(255, 255, 255, 0.3);
	box-shadow: inset 0 20px 30px rgba(255, 255, 255, 0.3);

	content: "";
    height: 180px;
	left: 10px;
	position: absolute;
	width: 180px;
}



</style>
</head>
<body style="background:url('https://media.istockphoto.com/photos/computer-notebook-laptop-on-table-at-electronics-store-in-shopping-picture-id918522004?k=6&m=918522004&s=170667a&w=0&h=zawuOeKJmG3HP8OLHUrWmAbPmLgFzYDpahy_XXCsHB0=')no-repeat;background-size:cover;">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Day Electronic</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a class="nav-link" href="{% url 'accounts:home' %}">Home</a></li>
      <li><a href="{% url 'accounts:about' %}">About Us</a></li>
      <li><a href="{% url 'accounts:contact' %}">Help</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'accounts:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <li><a href="{% url 'accounts:login' %}"><span><i class="bi bi-cart-fill teal-color"></i></span></a></li>
    </ul>
  </div>
</nav>
<div class="text-box">
  <p>Day</p>
  <h1>Electronics</h1>
  <h3>Home appliances and Electronic gadgets</h3>
  <div id="background-wrap">
    <div class="bubble x1"></div>
    <div class="bubble x2"></div>
    <div class="bubble x3"></div>
    <div class="bubble x4"></div>
    <div class="bubble x5"></div>
    <div class="bubble x6"></div>
    <div class="bubble x7"></div>
    <div class="bubble x8"></div>
    <div class="bubble x9"></div>
    <div class="bubble x10"></div>
</div>
</div>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/6421a61831ebfa0fe7f4ef43/1gshn1krj';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->


<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><span class="bi bi-facebook"></span></i></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><span class="bi bi-twitter"></i></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><span class="bi bi-google"></span></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><span class="bi bi-instagram"></span></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><span class="bi bi-linkedin"></span></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><span class="bi bi-github"></span></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    ©Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">Dayelectronic.com <i class="bi bi-bag"></i></a>
  </div>
  <!-- Copyright -->
</footer>
</body>
</html>

ecom_elec/templates/accounts/login.html
{% extends "accounts/header.html" %}

{% block content %}      

{% load crispy_forms_tags %}
<body style="background:url('https://media.istockphoto.com/photos/computer-notebook-laptop-on-table-at-electronics-store-in-shopping-picture-id918522004?k=6&m=918522004&s=170667a&w=0&h=zawuOeKJmG3HP8OLHUrWmAbPmLgFzYDpahy_XXCsHB0=')no-repeat;background-size:cover;">
<!--Login-->
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'accounts:register' %}">Create an account</a>.</p>
</div>

{% endblock %}

ecom_elec/templates/accounts/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


  <!-- Option 1: Include in HTML -->

    <title>Title</title>
</head>
<body>
<!--Navbar-->
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Dayelectronic</h5>
    <span class="text-muted">Login to Explore.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

</nav>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
</body>
</html>