ecom_elec/accounts/urls.py
from accounts .views import home,about,contact,cart

from django.urls import path
from . import views
from .views import Index

app_name = "accounts"


urlpatterns = [
        path("register", views.register_request, name="register"),
        path("login", views.login_request, name="login"),
        path('',Index.as_view(),name='index'),
        path('home/',home,name="home"),
        path('about/',about,name="about"),
        path('contact/',contact,name="contact"),
        path("cart/",cart,name="cart")


]

ecom_elec/ecom_elec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('electronics/',include("electronics.urls")),
    path('',include("accounts.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_elec/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
        .dropdown-toggle{
         color: white;
}
    </style>
</head>
<body>
<!--Nav Bar-->
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'list' %}" >DayElectricStore</a>
<!--      <img src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="Bootstrap" width="30" height="24">-->

      <div class="btn-group dropright">
      <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:20px">
              {{user}}
          </a>
<!--          Login conditions-->
          <div class="dropdown-menu">
              {%if user.is_authenticated%}
              <a class="dropdown-item" href="{% url 'accounts:home'%}">Logout</a>
              {% else %}
              <a class="dropdown-item text-secondary" href="{% url 'login'%}">Login</a>
              <a class="dropdown-item text-secondary" href="{% url 'register'%}">Register</a>
              {% endif %}
          </div>
      </div>
<div class="mx-auto" style="width:10px;">
      </div>

<!--Search-->
    <form class="search"action="{%url 'search' %}" method="get">
        <label>search</label>
    <input name="q"class="fas fa-search" type="text" autocomplete="on"
           placeholder="click to search">

        </form>

<!--    <div class="cart">-->
<!--            <h3>{{request.user}}</h3>-->

<!--            <a href="{% url 'accounts:cart' %}" style="color:white; text-decoration:none">-->
<!--                 <div class="cart-container">-->
<!--                    <div class="cartitems"><p id="num_of_items">{{cart.num_of_items}}</p></div>-->
<!--                    <i class="fa-solid fa-cart-shopping"></i>-->
<!--                </div>-->
<!--            </a>-->


<!--        </div>-->
    </nav>
<br><br>
{%block content %}

{%endblock %}
<!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>
</html>

ecom_elec/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <style>
button hover{
  color:Red;
  }
  </style>
</head>
<body style="background:url('https://t4.ftcdn.net/jpg/01/15/04/17/240_F_115041793_FZgCIE8USzIsi2MJudUMbVef3PiYSheX.jpg')no-repeat;background-size:cover;">
  <section class="vh-1000" style="color:Black";>
    <div class="container h-1000">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <p><span class="h2" style="color:Black";>Shopping Cart </span>
          {% for cart_item in cart_items %}
          <div class="card mb-4" style="color:red";>
            <div class="card-body p-4" style="color:red";>

              <div class="row align-items-center" style="color:red";>
                <div class="col-md-2" style="color:red";>
                  <img src="{{cart_item.image_url}}"
                    class="img-fluid" alt="Generic placeholder image">
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                  <div>
                    <p class="small text-muted mb-4 pb-2">Name</p>
                    <p class="lead fw-normal mb-0">{{ cart_item.product }}</p>
                  </div>
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                  <div>
                    <p class="small text-muted mb-4 pb-2">Quantity</p>
                    <p class="lead fw-normal mb-0">{{ cart_item.quantity }}</p>
                  </div>
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                  <div>
                    <p class="small text-muted mb-4 pb-2">Price:$</p>
                    <p class="lead fw-normal mb-0">{{ cart_item.price}}</p>
                  </div>
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                  <div>
                    <p class="small text-muted mb-4 pb-2">Remove</p>
                    <a href="{% url 'remove_from_cart' cart_item.id %}"><p class="lead fw-normal mb-0"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M135.2 17.7C140.6 6.8 151.7 0 163.8 0H284.2c12.1 0 23.2 6.8 28.6 17.7L320 32h96c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 96 0 81.7 0 64S14.3 32 32 32h96l7.2-14.3zM32 128H416V448c0 35.3-28.7 64-64 64H96c-35.3 0-64-28.7-64-64V128zm96 64c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16z"/></svg></p></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          <div class="card mb-5">
            <div class="card-body p-4">

              <div class="float-end">
                <p class="mb-0 me-5 d-flex align-items-center">
                  <span class="small text-muted me-2">Order total:</span> <span
                    class="lead fw-normal">${{ total }}</span>
                </p>
              </div>
            </div>
          </div>

          <div class="d-flex justify-content-left">
            {% if total == 0 %}
            <a href="{% url 'list' %}"><button type="button" class="btn btn-primary btn-lg ">Continue shopping</button></a>
            {% else %}
            <a href="{% url 'list' %}"><button type="button" class="btn btn-primary btn-lg ">Continue shopping</button></a>
            {% endif %}

          </div>

        </div>
      </div>
    </div>
  </section>
</body>

{% endblock %}

ecom_elec/templates/checkout.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta id="meta" name="viewport"
		content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>

    </style>
</head>
<body style="background:url('https://t4.ftcdn.net/jpg/01/15/04/17/240_F_115041793_FZgCIE8USzIsi2MJudUMbVef3PiYSheX.jpg')no-repeat;background-size:cover;">
<div class="container">
    {% if object.stock_availability is True %}
    <div class="row">
        <div class="col-lg">
            <div class="text-center" style="width:22rem;">
                <img src="{{object.image_url}}" class="card-img">
            </div>
        </div>
        <div class="col-lg">
            <br>
            <div class="card card-body">
                <h3>{{ object.name}}</h3>
                <br>
                <h4>Total:$-{{object.price|floatformat:2}}</h4>
                <hr>
                <div id="paypal-button-container"></div>
            <a href="{% url 'list' %}" class="btn btn-danger" role="button">Cancel Order</a>
                </div>

        </div>
    </div>
    {% endif %}
</div>
<!--Paypal payments-->

	<div id="paypal-button-container"></div>

	<script
		src="https://www.paypal.com/sdk/js?client-id=AaDbFCTAdi8NU4o-x6oOaBiLLoybkvO8w3xVZ2LgPAiTRwT4dDJu5u_ZecP9OtLTDvr7GZtZk_HuM3kq&currency=USD"></script>

	<script>

		function getCookie(name) {
			var cookieValue = null;
			if (document.cookie && document.cookie !== '') {
				var cookies = document.cookie.split(';');
				for (var i = 0; i < cookies.length; i++) {
					var cookie = cookies[i].trim();
					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) === (name + '=')) {
						cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
						break;
					}
				}
			}
			return cookieValue;
		}
		var csrftoken = getCookie('csrftoken');

		var total = '{{object.price}}'
		var productId = '{{object.id}}'

		function completeOrder() {
			var url = "{% url 'complete' %}"

			fetch(url, {
				method: 'POST',
				headers: {
					'content-type': 'application/json',
					'X-CSRFToken': csrftoken,
				},
				body: JSON.stringify({ 'productId': productId })
			})
		}



		// Render the PayPal button into #paypal-button-container
		paypal.Buttons({

			// Set up the transaction
			createOrder: function (data, actions) {
				return actions.order.create({
					purchase_units: [{
						amount: {
							value: total
						}
					}]
				});
			},

			// Finalize the transaction
			onApprove: function (data, actions) {
				return actions.order.capture().then(function (details) {
					// Show a success message to the buyer
					completeOrder()
					alert('Transaction completed by ' + details.payer.name.given_name + '!');
				});
			}


		}).render('#paypal-button-container');
	</script>
</body>
</html>
{% endblock content %}

ecom_elec/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .container { display: flex; align-items: stretch; justify-content: space-around; padding: 50px 0; }
    </style>
</head>
<body style="background:url('https://t4.ftcdn.net/jpg/01/15/04/17/240_F_115041793_FZgCIE8USzIsi2MJudUMbVef3PiYSheX.jpg')no-repeat;background-size:cover;">
<div class="container">
<div class="card" style="max-width:840px;height:350px;">
    <div class="row no-gutters">
    <div class="col-md-4">
        <img src="{{object.image_url}}" class="card-img">
    </div>

<div class="col-md-8">
    <div class="card-body">
        <h4 class="card-title">{{object.name }}</h4>
        <p class="card-text">{{object.description}}</p>
        <p>Price: $ {{ object.price|floatformat:2 }}</p>
        <p><a href="{{ object.follow_company }}" class="btn btn-info" role="button">Follow Company</a><p><a href="{% url 'add_to_cart' object.id %}" class="btn btn-outline-success" role="button">Add to cart</a>&nbsp<a href="{% url 'list' %}" class="btn btn-danger" role="button">Cancel Order</a></p>
        <p><a href="{% url 'add_to_fav' object.id %}" class="btn btn-outline-success" role="button">Add to Wishlist</a>
        {% if object.stock_availability is True %}
<a href="{% url 'checkout' object.id %}" class="btn btn-outline-success" role="button">Proceed to Pay</a>

{% else %}
<h4 class="text-danger">Out of Stock...!</h4>
{% endif %}
    </div>
    </div>
    </div>
</div>
</div>
</body>
</html>
{% endblock content %}

ecom_elec/templates/fav.html
{% extends 'base.html' %}

{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>

  .user-info-wrapper {
    position: relative;
    width: 100%;
    margin-bottom: -1px;
    padding-top: 90px;
    padding-bottom: 30px;
    border: 1px solid #e1e7ec;
    border-top-left-radius: 7px;
    border-top-right-radius: 7px;
    overflow: hidden
}

.user-info-wrapper .user-cover {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 120px;
    background-position: center;
    background-color: #f5f5f5;
    background-repeat: no-repeat;
    background-size: cover
}

.user-info-wrapper .user-cover .tooltip .tooltip-inner {
    width: 230px;
    max-width: 100%;
    padding: 10px 15px
}

.user-info-wrapper .info-label {
    display: block;
    position: absolute;
    top: 18px;
    right: 18px;
    height: 26px;
    padding: 0 12px;
    border-radius: 13px;
    background-color: #fff;
    color: #606975;
    font-size: 12px;
    line-height: 26px;
    box-shadow: 0 1px 5px 0 rgba(0, 0, 0, 0.18);
    cursor: pointer
}

.user-info-wrapper .info-label>i {
    display: inline-block;
    margin-right: 3px;
    font-size: 1.2em;
    vertical-align: middle
}

.user-info-wrapper .user-info {
    display: table;
    position: relative;
    width: 100%;
    padding: 0 18px;
    z-index: 5
}

.user-info-wrapper .user-info .user-avatar,
.user-info-wrapper .user-info .user-data {
    display: table-cell;
    vertical-align: top
}

.user-info-wrapper .user-info .user-avatar {
    position: relative;
    width: 115px
}

.user-info-wrapper .user-info .user-avatar>img {
    display: block;
    width: 100%;
    border: 5px solid #fff;
    border-radius: 50%
}

.user-info-wrapper .user-info .user-avatar .edit-avatar {
    display: block;
    position: absolute;
    top: -2px;
    right: 2px;
    width: 36px;
    height: 36px;
    transition: opacity .3s;
    border-radius: 50%;
    background-color: #fff;
    color: #606975;
    line-height: 34px;
    box-shadow: 0 1px 5px 0 rgba(0, 0, 0, 0.2);
    cursor: pointer;
    opacity: 0;
    text-align: center;
    text-decoration: none
}

.user-info-wrapper .user-info .user-avatar .edit-avatar::before {
    font-family: feather;
    font-size: 17px;
    content: '\e058'
}

.user-info-wrapper .user-info .user-avatar:hover .edit-avatar {
    opacity: 1
}

.user-info-wrapper .user-info .user-data {
    padding-top: 48px;
    padding-left: 12px
}

.user-info-wrapper .user-info .user-data h4 {
    margin-bottom: 2px
}

.user-info-wrapper .user-info .user-data span {
    display: block;
    color: #9da9b9;
    font-size: 13px
}

.user-info-wrapper+.list-group .list-group-item:first-child {
    border-radius: 0
}

.user-info-wrapper+.list-group .list-group-item:first-child {
    border-radius: 0;
}
.list-group-item:first-child {
    border-top-left-radius: 7px;
    border-top-right-radius: 7px;
}
.list-group-item:first-child {
    border-top-left-radius: .25rem;
    border-top-right-radius: .25rem;
}
a.list-group-item {
    padding-top: .87rem;
    padding-bottom: .87rem;
}
a.list-group-item, .list-group-item-action {
    transition: all .25s;
    color: Black;
    font-weight: 500;
}
.with-badge {
    position: relative;
    padding-right: 3.3rem;
}
.list-group-item {
    border-color: #e1e7ec;
    background-color: #fff;
    text-decoration: none;
}
.list-group-item {
    position: relative;
    display: block;
    padding: .75rem 1.25rem;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid rgba(0,0,0,0.125);
}

.shopping-cart,
.wishlist-table,
.order-table {
    margin-bottom: 20px
}

.shopping-cart .table,
.wishlist-table .table,
.order-table .table {
    margin-bottom: 0
}

.shopping-cart .btn,
.wishlist-table .btn,
.order-table .btn {
    margin: 0
}

.shopping-cart>table>thead>tr>th,
.shopping-cart>table>thead>tr>td,
.shopping-cart>table>tbody>tr>th,
.shopping-cart>table>tbody>tr>td,
.wishlist-table>table>thead>tr>th,
.wishlist-table>table>thead>tr>td,
.wishlist-table>table>tbody>tr>th,
.wishlist-table>table>tbody>tr>td,
.order-table>table>thead>tr>th,
.order-table>table>thead>tr>td,
.order-table>table>tbody>tr>th,
.order-table>table>tbody>tr>td {
    vertical-align: middle !important
}

.shopping-cart>table thead th,
.wishlist-table>table thead th,
.order-table>table thead th {
    padding-top: 17px;
    padding-bottom: 17px;
    border-width: 1px
}

.shopping-cart .remove-from-cart,
.wishlist-table .remove-from-cart,
.order-table .remove-from-cart {
    display: inline-block;
    color: #ff5252;
    font-size: 18px;
    line-height: 1;
    text-decoration: none
}

.shopping-cart .count-input,
.wishlist-table .count-input,
.order-table .count-input {
    display: inline-block;
    width: 100%;
    width: 86px
}

.shopping-cart .product-item,
.wishlist-table .product-item,
.order-table .product-item {
    display: table;
    width: 100%;
    min-width: 150px;
    margin-top: 5px;
    margin-bottom: 3px
}

.shopping-cart .product-item .product-thumb,
.shopping-cart .product-item .product-info,
.wishlist-table .product-item .product-thumb,
.wishlist-table .product-item .product-info,
.order-table .product-item .product-thumb,
.order-table .product-item .product-info {
    display: table-cell;
    vertical-align: top
}

.shopping-cart .product-item .product-thumb,
.wishlist-table .product-item .product-thumb,
.order-table .product-item .product-thumb {
    width: 130px;
    padding-right: 20px
}

.shopping-cart .product-item .product-thumb>img,
.wishlist-table .product-item .product-thumb>img,
.order-table .product-item .product-thumb>img {
    display: block;
    width: 100%
}

@media screen and (max-width: 860px) {
    .shopping-cart .product-item .product-thumb,
    .wishlist-table .product-item .product-thumb,
    .order-table .product-item .product-thumb {
        display: none
    }
}

.shopping-cart .product-item .product-info span,
.wishlist-table .product-item .product-info span,
.order-table .product-item .product-info span {
    display: block;
    font-size: 13px
}

.shopping-cart .product-item .product-info span>em,
.wishlist-table .product-item .product-info span>em,
.order-table .product-item .product-info span>em {
    font-weight: 500;
    font-style: normal
}

.shopping-cart .product-item .product-title,
.wishlist-table .product-item .product-title,
.order-table .product-item .product-title {
    margin-bottom: 6px;
    padding-top: 5px;
    font-size: 16px;
    font-weight: 500
}

.shopping-cart .product-item .product-title>a,
.wishlist-table .product-item .product-title>a,
.order-table .product-item .product-title>a {
    transition: color .3s;
    color:#000000;
    font-size:20px;
    line-height: 1.5;
    text-decoration: none
}

.shopping-cart .product-item .product-title>a:hover,
.wishlist-table .product-item .product-title>a:hover,
.order-table .product-item .product-title>a:hover {
    color:#Ff0000;
}

.shopping-cart .product-item .product-title small,
.wishlist-table .product-item .product-title small,
.order-table .product-item .product-title small {
    display: inline;
    margin-left: 6px;
    font-weight: 500
}

.wishlist-table .product-item .product-thumb {
    display: table-cell !important
}

@media screen and (max-width: 576px) {
    .wishlist-table .product-item .product-thumb {
        display: none !important
    }
}

.badge.badge-primary {
    background-color: #0da9ef;
}
.with-badge .badge {
    position: absolute;
    top: 50%;
    right: 1.15rem;
    -webkit-transform: translateY(-50%);
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
}
.list-group-item i {
    margin-top: -4px;
    margin-right: 8px;
    font-size: 1.1em;
}


</style>

<body style="background:url('https://t4.ftcdn.net/jpg/01/15/04/17/240_F_115041793_FZgCIE8USzIsi2MJudUMbVef3PiYSheX.jpg')no-repeat;background-size:cover;">
<div class="container padding-bottom-3x mb-2">
  <div class="row">      
      <div class="container padding-bottom-3x mb-2">
        <div class="col-lg-8">
            <div class="padding-top-2x mt-2 hidden-lg-up"></div>
            <!-- Wishlist Table-->
            <div class="table-responsive wishlist-table margin-bottom-none">
                <table class="table">
                    <tbody>
                      <tr>
                        <th>Product Name</th>
                    </tr>
                    {% for fav_item in favorite_items %}
                        <tr>
                            <td>
                                <div class="product-item">
                                    <a class="product-thumb" href="#"><img src="{{fav_item.image_url}}" alt="Product"></a>
                                    <div class="product-info">
                                        <h4 class="product-title"><a href="{% url 'detail-view' fav_item.id %}">{{fav_item.product}}</a></h4>
                                        <div class="text-lg text-medium text-muted-black";>${{fav_item.price}}</div>
                                        <div>Availability:
                                          {% if fav_item.stock_availability == True %}
                                          <div class="d-inline text-black">Availability<i class="fa fa-heart" style="font-size:18px;color:red"></i></div>
                                          {% else %}
                                          <div class="d-inline text-black" style="color:red;">Out of Stock</div>
                                          {% endif %}
                                        </div>
                                        <div>Remove Now:
                                        <a href="{% url 'remove_from_fav' fav_item.id %}"><div class="d-inline text-success"><i class="fa fa-heart" style="font-size:18px;color:black"></i></div></a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
            </div>
            
            <hr class="mb-4">
          
        </div>
    </div>
</div>
            
        
          <div class="d-flex justify-content-end">
            <a href="{% url 'list' %}"><button type="button" class="btn btn-light btn-lg ">Continue</button></a>
          </div>

 
</body>
{% endblock %}

ecom_elec/templates/list.html
{% extends 'base.html' %}
{% load static %}
.card
    {
        width: 29%;
        flex-wrap: wrap;
        flex: initial;
    }
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title><link rel="stylesheet" href="{% static 'css/list.css' %}">
</head>
{% block content %}
<body style="background:url('https://t4.ftcdn.net/jpg/01/15/04/17/240_F_115041793_FZgCIE8USzIsi2MJudUMbVef3PiYSheX.jpg')no-repeat;background-size:cover;">
<div class="container">
<div class="row">
    {% for each in object_list %}
    <div class="col-lg-3 d-flex align-items-stretch mt-5" >
        <div class="card" style="width: 500px; height:500px;">
            <img src="{{each.image_url}}" class="card-img-top" alt=".." width="300" height="300">
            <div class="card-body">
                <h5 class="card-title">{{each.name}}</h5>
                <p class="card-text">${{each.price|floatformat:2}}</p>
                {% if each.stock_availability is True %}
                <button type="button" class="btn btn-success">Available</button>
                {% else %}
                <button type="button" class="btn btn-danger">Out of stock</button>
                {% endif %}
                <a href="{% url 'detail-view' each.id %}" class="btn btn-primary">View</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
    </div>
</body>
{% endblock content %}
</html>

ecom_elec/templates/search.html
{% extends 'base.html' %}
{% block title  %}Search {% endblock title%}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background:url('https://t4.ftcdn.net/jpg/01/15/04/17/240_F_115041793_FZgCIE8USzIsi2MJudUMbVef3PiYSheX.jpg')no-repeat;background-size:cover;">
<h3 class="text-secondary text-dark">Search Results:</h3>
  {% for every in object_list %}
  <div class="container">
      <h3 ><a href="{% url 'detail-view' every.pk %}" style="text-decoration: none;color:white;">{{every.name}}</a></h3>
      <p>Company:{{every.Company}}</p>
  </div>
{% empty %}
<h5 class="text-danger">Nothing Found:(</h5>
{% endfor %}
</body>
</html>
{% endblock content %}